{ "screen_name" : "CdnClubVan" }
{ "screen_name" : "AndersFalk2" }
{ "screen_name" : "DTESGreenWaste" }
{ "screen_name" : "PeopleTreeLearn" }
{ "screen_name" : "Katreenaw" }
{ "screen_name" : "mike_schneider_" }
{ "screen_name" : "Green_ByAdera" }
{ "screen_name" : "NEXTEnviroBC" }
{ "screen_name" : "sunflower_sk" }
{ "screen_name" : "urbanracks" }
{ "screen_name" : "BCConstructionA" }
{ "screen_name" : "MovieYearbook" }
{ "screen_name" : "Chantel_Dawn" }
{ "screen_name" : "Senz_Says" }
{ "screen_name" : "hello_charity" }
{ "screen_name" : "VinciParkCanada" }
{ "screen_name" : "MMCDAssoc" }
{ "screen_name" : "IAMTONY1" }
{ "screen_name" : "SeaWallAgency" }
{ "screen_name" : "urbngreen" }
{ "screen_name" : "SFUPublicSquare" }
{ "screen_name" : "MacCanada" }
{ "screen_name" : "Divorce_Shop" }
{ "screen_name" : "chelaland" }
{ "screen_name" : "robchantler" }
{ "screen_name" : "SatelEnt" }
{ "screen_name" : "VanCentreNDP" }
{ "screen_name" : "BESTCARSBC" }
{ "screen_name" : "Rocalyne" }
{ "screen_name" : "BCEIA_" }
{ "screen_name" : "GerryTMcGuire" }
{ "screen_name" : "andrealcaesar" }
{ "screen_name" : "uprisingbreads" }
{ "screen_name" : "Paulyy_P" }
{ "screen_name" : "CivlNews" }
{ "screen_name" : "SeanThor16" }
{ "screen_name" : "fonikdesign" }
{ "screen_name" : "KlahowyaVillage" }
{ "screen_name" : "WaiLui" }
{ "screen_name" : "OddballWorkshop" }
{ "screen_name" : "BitCase" }
{ "screen_name" : "jacsrons" }
{ "screen_name" : "Miss604" }
{ "screen_name" : "avanbaarsen" }
{ "screen_name" : "PL__Web" }
{ "screen_name" : "Deannaz88" }
{ "screen_name" : "DimitryMorales" }
{ "screen_name" : "alittlemoregood" }
{ "screen_name" : "VisionVancouver" }
{ "screen_name" : "Spennynub" }
{ "screen_name" : "waldorfhotel" }
{ "screen_name" : "GreekDay" }
{ "screen_name" : "lisagfisher" }
{ "screen_name" : "rj_aquino" }
{ "screen_name" : "SUVCC" }
{ "screen_name" : "nredmond" }
{ "screen_name" : "slowfade" }
{ "screen_name" : "totochow" }
{ "screen_name" : "climatesmart" }
{ "screen_name" : "orcasislandtv" }
{ "screen_name" : "BigBrosOnline" }
{ "screen_name" : "amygibson" }
{ "screen_name" : "lizsperandeo" }
{ "screen_name" : "djdimitri_gr" }
{ "screen_name" : "OutSmarts" }
{ "screen_name" : "KeithIppel" }
{ "screen_name" : "EricGWan" }
{ "screen_name" : "TripsForKidsVan" }
{ "screen_name" : "VanObserver" }
{ "screen_name" : "RobCottingham" }
{ "screen_name" : "Vida_Jay" }
{ "screen_name" : "DuncanWlod" }
{ "screen_name" : "ashiqahamed" }
{ "screen_name" : "energy_matters" }
{ "screen_name" : "sengsengsavanh" }
{ "screen_name" : "anthonyctaylor" }
{ "screen_name" : "aimeearama" }
{ "screen_name" : "crisiscentrebc" }
{ "screen_name" : "BW_Creative" }
{ "screen_name" : "rvossepoel" }
{ "screen_name" : "KristenThom" }
{ "screen_name" : "dewert" }
{ "screen_name" : "kalinhop" }
{ "screen_name" : "mandablemac" }
{ "screen_name" : "chickievan" }
{ "screen_name" : "rcc_heritage" }
{ "screen_name" : "bartdebaere" }
{ "screen_name" : "colbeaner" }
{ "screen_name" : "KudosKvetches" }
{ "screen_name" : "GalaxyPlumbing" }
{ "screen_name" : "G3OP" }
{ "screen_name" : "iheartcities" }
{ "screen_name" : "kpapp" }
{ "screen_name" : "CorrinSkalbeck" }
{ "screen_name" : "kathiewallace" }
{ "screen_name" : "d_everett" }
{ "screen_name" : "parkinnvan" }
{ "screen_name" : "rmountaineer" }
{ "screen_name" : "erikoarai" }
{ "screen_name" : "shawnalum" }
{ "screen_name" : "jl_d" }
{ "screen_name" : "BoffoProperties" }
{ "screen_name" : "SkyTrainLady" }
{ "screen_name" : "theprovince" }
{ "screen_name" : "jminter" }
{ "screen_name" : "PlayhouseWine" }
{ "screen_name" : "camera_junkie" }
{ "screen_name" : "Synergist_Inc" }
{ "screen_name" : "Stv" }
{ "screen_name" : "BobRansford" }
{ "screen_name" : "SteveWooBCN" }
{ "screen_name" : "CityCaucus" }
{ "screen_name" : "HealingPod" }
{ "screen_name" : "RobsonStreet" }
{ "screen_name" : "ScienceWorldTR" }
{ "screen_name" : "IFestCanada" }
{ "screen_name" : "lwong76" }
{ "screen_name" : "bc_living" }
{ "screen_name" : "SauderISIS" }
{ "screen_name" : "ChanCentre" }
{ "screen_name" : "dennisworld" }
{ "screen_name" : "Jesswakeman" }
{ "screen_name" : "cyclevancity" }
{ "screen_name" : "stephenhui" }
{ "screen_name" : "MacKenzieCam" }
{ "screen_name" : "thebuzzer" }
{ "screen_name" : "jmv" }
{ "screen_name" : "envirodefence" }
{ "screen_name" : "h_mllr" }
{ "screen_name" : "mattsayswhat" }
{ "screen_name" : "gordonr" }
{ "screen_name" : "paulhillsdon" }
{ "screen_name" : "CWFMrobson" }
{ "screen_name" : "MonasLebanese" }
{ "screen_name" : "WatertigerBC" }
{ "screen_name" : "vpsn" }
{ "screen_name" : "anncheng" }
{ "screen_name" : "rtanglao" }
{ "screen_name" : "EllenYeung" }
{ "screen_name" : "MichaelSSU" }
{ "screen_name" : "drjotisamra" }
{ "screen_name" : "ride2rio" }
{ "screen_name" : "VC_Ocean" }
{ "screen_name" : "homelessaction" }
{ "screen_name" : "prog_grooves" }
{ "screen_name" : "LMoffatt" }
{ "screen_name" : "CamaraEcuaCanad" }
{ "screen_name" : "MarlaGuloien" }
{ "screen_name" : "burrowingsnow" }
{ "screen_name" : "JRad_33" }
{ "screen_name" : "JJMacLean" }
{ "screen_name" : "icompasstech" }
{ "screen_name" : "FreeTalkTV" }
{ "screen_name" : "GILibertywine" }
{ "screen_name" : "AmandaLeeL" }
{ "screen_name" : "INTCROWDMGMT" }
{ "screen_name" : "DiyoboVancouver" }
{ "screen_name" : "chantelsstuff" }
{ "screen_name" : "MicroMixUSA" }
{ "screen_name" : "PR_Associates" }
{ "screen_name" : "venus_fitness" }
{ "screen_name" : "Encorebuildings" }
{ "screen_name" : "creeksiderec" }
{ "screen_name" : "TrailSkinz" }
{ "screen_name" : "canadamais" }
{ "screen_name" : "savestpauls" }
{ "screen_name" : "herongzao" }
{ "screen_name" : "jdumrique" }
{ "screen_name" : "MrGayCanada" }
{ "screen_name" : "resonantmind" }
{ "screen_name" : "TheCityonCiTR" }
{ "screen_name" : "MetroGnomeLawn" }
{ "screen_name" : "dedamarketing" }
{ "screen_name" : "kimnursall" }
{ "screen_name" : "Horizonlsc" }
{ "screen_name" : "BCusedcars" }
{ "screen_name" : "JessEats" }
{ "screen_name" : "BCgrapegal" }
{ "screen_name" : "DavidVion" }
{ "screen_name" : "securiguard" }
{ "screen_name" : "Hey_AC" }
{ "screen_name" : "7ElevenCanada" }
{ "screen_name" : "triayconsulting" }
{ "screen_name" : "climatetoolkit" }
{ "screen_name" : "PICSSociety" }
{ "screen_name" : "globeretail" }
{ "screen_name" : "na9hc" }
{ "screen_name" : "andrewconsiders" }
{ "screen_name" : "THECEDARGUY" }
{ "screen_name" : "BlackShieldPS" }
{ "screen_name" : "YourDDS" }
{ "screen_name" : "LGHThriftShop" }
{ "screen_name" : "trevorbowden" }
{ "screen_name" : "MarpoleMatters" }
{ "screen_name" : "flatheadwild" }
{ "screen_name" : "BreezeByAdera" }
{ "screen_name" : "bcboattours" }
{ "screen_name" : "hdtvdctsales" }
{ "screen_name" : "Dine2U" }
{ "screen_name" : "BurnabyBOT" }
{ "screen_name" : "South_Hill" }
{ "screen_name" : "realestateZOOM" }
{ "screen_name" : "thevancouvemove" }
{ "screen_name" : "jakecornejo" }
{ "screen_name" : "604Pulse" }
{ "screen_name" : "janicevillage" }
{ "screen_name" : "Improvanywhere" }
{ "screen_name" : "infinitifloors" }
{ "screen_name" : "_Big_SAM" }
{ "screen_name" : "PASTA4KIDZ" }
{ "screen_name" : "MerduEste" }
{ "screen_name" : "dfly_solutions" }
{ "screen_name" : "eco_svc" }
{ "screen_name" : "AragonProperty" }
{ "screen_name" : "AddImpact" }
{ "screen_name" : "OJsSurrey" }
{ "screen_name" : "hcma" }
{ "screen_name" : "NuclearHair" }
{ "screen_name" : "jptruman" }
{ "screen_name" : "connorm_19" }
{ "screen_name" : "Foundationmortg" }
{ "screen_name" : "ajwinfo" }
{ "screen_name" : "ICECanada" }
{ "screen_name" : "cwilhelmson" }
{ "screen_name" : "VKingsway" }
{ "screen_name" : "ampwilson" }
{ "screen_name" : "BCFurnace" }
{ "screen_name" : "Headhancho88" }
{ "screen_name" : "vquirino" }
{ "screen_name" : "EarthRunFdn" }
{ "screen_name" : "true_recovery" }
{ "screen_name" : "digarc" }
{ "screen_name" : "MoreHomes4" }
{ "screen_name" : "BaysideLounge1" }
{ "screen_name" : "RobPearlman" }
{ "screen_name" : "KoreChiroVan" }
{ "screen_name" : "pieglue" }
{ "screen_name" : "2012xx2012" }
{ "screen_name" : "TransportChris" }
{ "screen_name" : "thetransitfan" }
{ "screen_name" : "16letterusernam" }
{ "screen_name" : "SouthArmAuto" }
{ "screen_name" : "creativecity" }
{ "screen_name" : "SarahRuediger" }
{ "screen_name" : "doflo18" }
{ "screen_name" : "JiffyMove" }
{ "screen_name" : "AlbertBayburin" }
{ "screen_name" : "LangleyAwning" }
{ "screen_name" : "LegacyLiquor" }
{ "screen_name" : "VancouverKia" }
{ "screen_name" : "TracyHelbert" }
{ "screen_name" : "nickamado" }
{ "screen_name" : "suclapham" }
{ "screen_name" : "1CrashIs2Many" }
{ "screen_name" : "jay_soda" }
{ "screen_name" : "OOmoversca" }
{ "screen_name" : "nathancullen" }
{ "screen_name" : "WindsorCastleBB" }
{ "screen_name" : "MiquelDangeli" }
{ "screen_name" : "artworkstudioca" }
{ "screen_name" : "TerraBreads" }
{ "screen_name" : "amandhir711" }
{ "screen_name" : "julia_mhall" }
{ "screen_name" : "TalentFactory1" }
{ "screen_name" : "chemistrychad" }
{ "screen_name" : "PnkHollywood" }
{ "screen_name" : "KurtisKolt" }
{ "screen_name" : "WaggingTrails" }
{ "screen_name" : "MJAKing" }
{ "screen_name" : "ardvarkrobinson" }
{ "screen_name" : "Vancorder" }
{ "screen_name" : "KineticFamily" }
{ "screen_name" : "celesteAJ" }
{ "screen_name" : "antonson1" }
{ "screen_name" : "GitHayetsk" }
{ "screen_name" : "ebbymohseni" }
{ "screen_name" : "Tradeworks2" }
{ "screen_name" : "JennCarreiro" }
{ "screen_name" : "shamelesshussy" }
{ "screen_name" : "HeyApeRil" }
{ "screen_name" : "VancouverBCBuzz" }
{ "screen_name" : "Conquer180" }
{ "screen_name" : "jamie_lwalker" }
{ "screen_name" : "nubatown" }
{ "screen_name" : "Zazimullah" }
{ "screen_name" : "amcanblinds" }
{ "screen_name" : "HausofKolbee" }
{ "screen_name" : "deejlam" }
{ "screen_name" : "benwilson1130" }
{ "screen_name" : "TourismCollege1" }
{ "screen_name" : "JunieWu" }
{ "screen_name" : "PizzaPieman" }
{ "screen_name" : "DogGoneBeauty" }
{ "screen_name" : "danielajoness" }
{ "screen_name" : "chandrawu" }
{ "screen_name" : "BikingWarWounds" }
{ "screen_name" : "GLOBE_Series" }
{ "screen_name" : "JohnShelling" }
{ "screen_name" : "rachelrocks147" }
{ "screen_name" : "BCRealEstate1" }
{ "screen_name" : "GWGraphics" }
{ "screen_name" : "adichuchu" }
{ "screen_name" : "SustainaSaanich" }
{ "screen_name" : "PatrickMcCrea1" }
{ "screen_name" : "PowerStrata" }
{ "screen_name" : "nancywickham" }
{ "screen_name" : "madheavenk" }
{ "screen_name" : "FVConservancy" }
{ "screen_name" : "tracyrawa" }
{ "screen_name" : "RUNVAN_rdjordan" }
{ "screen_name" : "thetravelmaster" }
{ "screen_name" : "WonderettesVan" }
{ "screen_name" : "deecee604" }
{ "screen_name" : "yamolajoda" }
{ "screen_name" : "ninjaKarma" }
{ "screen_name" : "manveetvirk" }
{ "screen_name" : "miss_jenK" }
{ "screen_name" : "BuyRIC" }
{ "screen_name" : "Ish39" }
{ "screen_name" : "3citigroup" }
{ "screen_name" : "mpivon" }
{ "screen_name" : "bobby_purba" }
{ "screen_name" : "BabeCoal" }
{ "screen_name" : "PLInVancity" }
{ "screen_name" : "JOurom" }
{ "screen_name" : "Canucks_Brooke" }
{ "screen_name" : "VanCentralHI" }
{ "screen_name" : "AndreaSeale" }
{ "screen_name" : "VanExtendedStay" }
{ "screen_name" : "fido_mydog" }
{ "screen_name" : "Manji1947" }
{ "screen_name" : "lara_walters" }
{ "screen_name" : "ParkAidApp" }
{ "screen_name" : "TWFabShop" }
{ "screen_name" : "furryornot" }
{ "screen_name" : "CitytvNews" }
{ "screen_name" : "CityHallWchVAN" }
{ "screen_name" : "canucksfanraji" }
{ "screen_name" : "MahjerNews" }
{ "screen_name" : "WendyDphoto" }
{ "screen_name" : "COMPBLINDS" }
{ "screen_name" : "gwinterbottom" }
{ "screen_name" : "fabufit" }
{ "screen_name" : "OldHouseVillage" }
{ "screen_name" : "TheForumHouse" }
{ "screen_name" : "Mrs__Stanton" }
{ "screen_name" : "Mike_Killeen" }
{ "screen_name" : "Abdul_saad1" }
{ "screen_name" : "El_taco_paco" }
{ "screen_name" : "Nestah14" }
{ "screen_name" : "MeredithGeddes" }
{ "screen_name" : "DNV_Snow" }
{ "screen_name" : "louieseries" }
{ "screen_name" : "RCCSYouth" }
{ "screen_name" : "angewfoster" }
{ "screen_name" : "LuigiTuriano" }
{ "screen_name" : "ShopWest4th" }
{ "screen_name" : "ElkePorter" }
{ "screen_name" : "wentingw" }
{ "screen_name" : "RealtyShare" }
{ "screen_name" : "AIMMedical" }
{ "screen_name" : "Earthplaces" }
{ "screen_name" : "neroglobal" }
{ "screen_name" : "TurnLeafConsult" }
{ "screen_name" : "GoPlanbook" }
{ "screen_name" : "SecondaryTask" }
{ "screen_name" : "kar1ponat" }
{ "screen_name" : "ttara" }
{ "screen_name" : "TrevDeeleyHD" }
{ "screen_name" : "rosmotron" }
{ "screen_name" : "pinoypridevan" }
{ "screen_name" : "lestwarog" }
{ "screen_name" : "VanPostcardHD" }
{ "screen_name" : "she_loves_wine" }
{ "screen_name" : "FreeNewWebAds" }
{ "screen_name" : "bcgarlic" }
{ "screen_name" : "traceymaemiller" }
{ "screen_name" : "p_clair" }
{ "screen_name" : "WKVancouver" }
{ "screen_name" : "AnitaVoiceA" }
{ "screen_name" : "getdesigning" }
{ "screen_name" : "Vancouver_Plus" }
{ "screen_name" : "fortlangleybia" }
{ "screen_name" : "AJCrawford604" }
{ "screen_name" : "BCJob_Search" }
{ "screen_name" : "absolutestaffnc" }
{ "screen_name" : "NorthernTickets" }
{ "screen_name" : "rephard" }
{ "screen_name" : "scyofbc" }
{ "screen_name" : "ActorsUnlimited" }
{ "screen_name" : "InterFitSociety" }
{ "screen_name" : "SFUSCC" }
{ "screen_name" : "xpublicdefender" }
{ "screen_name" : "SSULive" }
{ "screen_name" : "fdmvancouver" }
{ "screen_name" : "jamievala" }
{ "screen_name" : "JasonCattermole" }
{ "screen_name" : "CanadaLadder" }
{ "screen_name" : "AdGirlsOrg" }
{ "screen_name" : "SuttonPlaceVan" }
{ "screen_name" : "_dianahu" }
{ "screen_name" : "LyssaCoon" }
{ "screen_name" : "jerrythefrienly" }
{ "screen_name" : "BCRenalAgency" }
{ "screen_name" : "tidbitsvan" }
{ "screen_name" : "JackieMaclean" }
{ "screen_name" : "Jobsvancouver1" }
{ "screen_name" : "faperello" }
{ "screen_name" : "ArtsFutureYVR" }
{ "screen_name" : "Jess_YVR" }
{ "screen_name" : "bogberry" }
{ "screen_name" : "missmagicapple" }
{ "screen_name" : "nate_pope" }
{ "screen_name" : "RCDGDentist" }
{ "screen_name" : "NewToVancouver" }
{ "screen_name" : "VancouverCondo1" }
{ "screen_name" : "summerfieldhome" }
{ "screen_name" : "domdom_woo" }
{ "screen_name" : "effwords" }
{ "screen_name" : "agardenca" }
{ "screen_name" : "maiannam" }
{ "screen_name" : "JoelWWood" }
{ "screen_name" : "AderaHome" }
{ "screen_name" : "moderncatalyst" }
{ "screen_name" : "flashgordo12" }
{ "screen_name" : "activelyme" }
{ "screen_name" : "CircadianGroup" }
{ "screen_name" : "TimesTelecomHUD" }
{ "screen_name" : "AlexandriaMitch" }
{ "screen_name" : "schwampsicle" }
{ "screen_name" : "frenchpressme" }
{ "screen_name" : "GeeksAfterDark" }
{ "screen_name" : "onebigmovement" }
{ "screen_name" : "shuji120792" }
{ "screen_name" : "scottperrie" }
{ "screen_name" : "knifaynat" }
{ "screen_name" : "AnthonyNSmith" }
{ "screen_name" : "RyaKobewka" }
{ "screen_name" : "Bettys_Cleaning" }
{ "screen_name" : "ScarletTapasLou" }
{ "screen_name" : "Pri4Parks" }
{ "screen_name" : "RajiKaur" }
{ "screen_name" : "FaithRV" }
{ "screen_name" : "thorstenphotogr" }
{ "screen_name" : "bronniep" }
{ "screen_name" : "Philzkidz" }
{ "screen_name" : "CommonEnergyUBC" }
{ "screen_name" : "tarafiied" }
{ "screen_name" : "ctdahl" }
{ "screen_name" : "GYVOca" }
{ "screen_name" : "LilyHarvey" }
{ "screen_name" : "BinionOpinion" }
{ "screen_name" : "SamanthaRG" }
{ "screen_name" : "AvedaRobson" }
{ "screen_name" : "DefinitelyVan" }
{ "screen_name" : "ctvmijunglee" }
{ "screen_name" : "WhistlerFriend" }
{ "screen_name" : "quinn_runkle" }
{ "screen_name" : "RegencyVanCity" }
{ "screen_name" : "TtGSDN" }
{ "screen_name" : "kylefarq" }
{ "screen_name" : "WestCoastGal75" }
{ "screen_name" : "vanoccupied" }
{ "screen_name" : "TimmysTelethon" }
{ "screen_name" : "LAVADining" }
{ "screen_name" : "Bob_Bose_SCC" }
{ "screen_name" : "PatricksGDC" }
{ "screen_name" : "SouthhillVan" }
{ "screen_name" : "lindzmarsh" }
{ "screen_name" : "nsvancouver" }
{ "screen_name" : "jescagraves" }
{ "screen_name" : "StopBillboard" }
{ "screen_name" : "lorinakeery" }
{ "screen_name" : "Vancouver_Mayor" }
{ "screen_name" : "StopSmrtMeterBC" }
{ "screen_name" : "jacobix" }
{ "screen_name" : "MARYBALLEZA" }
{ "screen_name" : "Classic_Teak" }
{ "screen_name" : "RachelymHo" }
{ "screen_name" : "Pamasslate" }
{ "screen_name" : "Liza_Rogers" }
{ "screen_name" : "DLaurieBF" }
{ "screen_name" : "jennyrationx" }
{ "screen_name" : "vancityjam2011" }
{ "screen_name" : "FreshOutlook" }
{ "screen_name" : "sarah_taher" }
{ "screen_name" : "vancouverscan" }
{ "screen_name" : "ei_van" }
{ "screen_name" : "LexaHobenshield" }
{ "screen_name" : "WHATthaFOSS" }
{ "screen_name" : "ohminbak" }
{ "screen_name" : "OutAndAboutYVR" }
{ "screen_name" : "QueenoftheParks" }
{ "screen_name" : "KarmaDLee" }
{ "screen_name" : "GECCoop" }
{ "screen_name" : "De4Council" }
{ "screen_name" : "DavidValente" }
{ "screen_name" : "Cinecraig" }
{ "screen_name" : "MMEventsInc" }
{ "screen_name" : "IEC_BC" }
{ "screen_name" : "odinperez" }
{ "screen_name" : "sendabottle" }
{ "screen_name" : "ParharD" }
{ "screen_name" : "VanSocialPolicy" }
{ "screen_name" : "FortisBC" }
{ "screen_name" : "votebettervsb" }
{ "screen_name" : "TantraMassageBC" }
{ "screen_name" : "goolsofjewels" }
{ "screen_name" : "GillsterMEDIA" }
{ "screen_name" : "CanAmSecurity" }
{ "screen_name" : "teerance" }
{ "screen_name" : "marco_aquila" }
{ "screen_name" : "NSPartyBags" }
{ "screen_name" : "mktgmentress" }
{ "screen_name" : "TeamPAL" }
{ "screen_name" : "xiyonce" }
{ "screen_name" : "Afuwa_" }
{ "screen_name" : "VanLimo" }
{ "screen_name" : "YVRcondos" }
{ "screen_name" : "vlopeza" }
{ "screen_name" : "W2Radio" }
{ "screen_name" : "__JLee" }
{ "screen_name" : "ToriesParty" }
{ "screen_name" : "VanAFL" }
{ "screen_name" : "sgulati" }
{ "screen_name" : "GeoffN28" }
{ "screen_name" : "AphrodisiacShop" }
{ "screen_name" : "sarenatalbot" }
{ "screen_name" : "CowleyCouncil" }
{ "screen_name" : "ThinkVanCity" }
{ "screen_name" : "LindaGilmaster" }
{ "screen_name" : "penguinstorm" }
{ "screen_name" : "JustinC009" }
{ "screen_name" : "PlaceSpeak" }
{ "screen_name" : "seramarieblaze" }
{ "screen_name" : "Garossino" }
{ "screen_name" : "RawCanvas" }
{ "screen_name" : "jeanhakizimana" }
{ "screen_name" : "LookoutSociety" }
{ "screen_name" : "pizzafreshslice" }
{ "screen_name" : "RockwellsOnline" }
{ "screen_name" : "monikapearl" }
{ "screen_name" : "UnionFoodMarket" }
{ "screen_name" : "vanvotes" }
{ "screen_name" : "Joanne_See" }
{ "screen_name" : "SurreyBCRealtor" }
{ "screen_name" : "ROYLandscape" }
{ "screen_name" : "nickmjow" }
{ "screen_name" : "RichportFord" }
{ "screen_name" : "604ster" }
{ "screen_name" : "VancouverBeacon" }
{ "screen_name" : "PCDentalGroup" }
{ "screen_name" : "Zedamark" }
{ "screen_name" : "TranBC_LMD" }
{ "screen_name" : "KDentistry" }
{ "screen_name" : "kcabor" }
{ "screen_name" : "LaurelGi" }
{ "screen_name" : "raincityparent" }
{ "screen_name" : "123_Dentist" }
{ "screen_name" : "PeterProHST" }
{ "screen_name" : "DrKenPhillips" }
{ "screen_name" : "s_martphones" }
{ "screen_name" : "SkillsChildCare" }
{ "screen_name" : "EcoHomeSpa" }
{ "screen_name" : "adixon77" }
{ "screen_name" : "LouieJacqueline" }
{ "screen_name" : "aimeegrane" }
{ "screen_name" : "cliqzvancouver" }
{ "screen_name" : "DreamRental" }
{ "screen_name" : "CarlosLins_CA" }
{ "screen_name" : "acleanvancouver" }
{ "screen_name" : "VancouverBCgift" }
{ "screen_name" : "sarahkstoner" }
{ "screen_name" : "dena_girl" }
{ "screen_name" : "PepperWireless" }
{ "screen_name" : "6044424604" }
{ "screen_name" : "eliteelecbikes" }
{ "screen_name" : "tawnya84" }
{ "screen_name" : "StephBlizzack" }
{ "screen_name" : "liquiddeli" }
{ "screen_name" : "Jeffwonef" }
{ "screen_name" : "davesgeekyideas" }
{ "screen_name" : "WendyLind" }
{ "screen_name" : "Aimee_CAPS2012" }
{ "screen_name" : "StraightLGBT" }
{ "screen_name" : "1HateOfTheWeek" }
{ "screen_name" : "MYRASystems" }
{ "screen_name" : "LangleyWellness" }
{ "screen_name" : "lifemovesca" }
{ "screen_name" : "RotaryAwards" }
{ "screen_name" : "melaniemcshim" }
{ "screen_name" : "lee_johnso" }
{ "screen_name" : "jdubcon77" }
{ "screen_name" : "CJVanc" }
{ "screen_name" : "ShawSabey" }
{ "screen_name" : "minney69" }
{ "screen_name" : "jennyscribbles" }
{ "screen_name" : "BaillieIan" }
{ "screen_name" : "jesswads" }
{ "screen_name" : "jeffrotin" }
{ "screen_name" : "KimMack92" }
{ "screen_name" : "alyski" }
{ "screen_name" : "tyler_bryant" }
{ "screen_name" : "NatalinaK" }
{ "screen_name" : "BastianZeiger" }
{ "screen_name" : "AlanoEdzerza" }
{ "screen_name" : "Elia_White" }
{ "screen_name" : "devotedforlife" }
{ "screen_name" : "teachertong" }
{ "screen_name" : "ShieldMasonry" }
{ "screen_name" : "TheCyclingWolf" }
{ "screen_name" : "GoldenGreatWall" }
{ "screen_name" : "yukon_scott" }
{ "screen_name" : "AarmitaC" }
{ "screen_name" : "MarcieTrevisan5" }
{ "screen_name" : "BusyBee_RRU" }
{ "screen_name" : "deleriyes" }
{ "screen_name" : "whalesafaris" }
{ "screen_name" : "EarthFound" }
{ "screen_name" : "TheDangerousExp" }
{ "screen_name" : "Canucks_Dream" }
{ "screen_name" : "GenYExcellence" }
{ "screen_name" : "DavidLalonde" }
{ "screen_name" : "PopaFatt" }
{ "screen_name" : "OlmaniDev" }
{ "screen_name" : "Khanhharoy" }
{ "screen_name" : "HeyVancouver" }
{ "screen_name" : "LanesideDesign" }
{ "screen_name" : "jenscott47" }
{ "screen_name" : "alisonesc" }
{ "screen_name" : "misandi" }
{ "screen_name" : "roseofeurope" }
{ "screen_name" : "kianaheighton" }
{ "screen_name" : "SarahSaysStuff" }
{ "screen_name" : "angelawong_" }
{ "screen_name" : "24hoursvan" }
{ "screen_name" : "mdayw" }
{ "screen_name" : "BCBusinessBeat" }
{ "screen_name" : "hraisinghani" }
{ "screen_name" : "JohnLee594" }
{ "screen_name" : "birdonawireart" }
{ "screen_name" : "sellinvancouver" }
{ "screen_name" : "mostlydana" }
{ "screen_name" : "FrontlineRE" }
{ "screen_name" : "TraumaScnClnUp" }
{ "screen_name" : "envtsustainvan" }
{ "screen_name" : "AlleyHealthFair" }
{ "screen_name" : "pastrytraining" }
{ "screen_name" : "ConstanceBarnes" }
{ "screen_name" : "thomas_lattimer" }
{ "screen_name" : "DaniellePresto" }
{ "screen_name" : "fetchcom" }
{ "screen_name" : "Urban_Gate" }
{ "screen_name" : "AzureProperties" }
{ "screen_name" : "i_am_slam" }
{ "screen_name" : "jma123123" }
{ "screen_name" : "JerrisonOracion" }
{ "screen_name" : "amblesideNOW" }
{ "screen_name" : "PhilippeLucas_" }
{ "screen_name" : "Hapapalooza" }
{ "screen_name" : "WebByBrad" }
{ "screen_name" : "ollietwist73" }
{ "screen_name" : "BikeboxCanada" }
{ "screen_name" : "AFJackson" }
{ "screen_name" : "ElCaminoCafe" }
{ "screen_name" : "sabriccardi" }
{ "screen_name" : "jcnarvey" }
{ "screen_name" : "Sunrise604" }
{ "screen_name" : "RainforestRoof" }
{ "screen_name" : "thinkjulie" }
{ "screen_name" : "JustAMurphy" }
{ "screen_name" : "mikesfinephotos" }
{ "screen_name" : "LiveSmartBCca" }
{ "screen_name" : "pattibacchus" }
{ "screen_name" : "Offsetters" }
{ "screen_name" : "Kanada_life" }
{ "screen_name" : "WorldinaGarden" }
{ "screen_name" : "buyinvancouver" }
{ "screen_name" : "dpiterritorial" }
{ "screen_name" : "burnabyid" }
{ "screen_name" : "CambieVillageBA" }
{ "screen_name" : "BuiltSpace" }
{ "screen_name" : "Heartly47" }
{ "screen_name" : "latincouver" }
{ "screen_name" : "edhsu604" }
{ "screen_name" : "VancityPhotos" }
{ "screen_name" : "Flavia_Z" }
{ "screen_name" : "IW_ColinOHearn" }
{ "screen_name" : "HeathDoi" }
{ "screen_name" : "Karenbc23" }
{ "screen_name" : "kurtisstewart" }
{ "screen_name" : "SS_Coffee" }
{ "screen_name" : "DanPagan" }
{ "screen_name" : "dashenta" }
{ "screen_name" : "StRegisBarGrill" }
{ "screen_name" : "LawsonRJ" }
{ "screen_name" : "VillageNowNet" }
{ "screen_name" : "MyYogiberry" }
{ "screen_name" : "swirsten" }
{ "screen_name" : "manchesterbar" }
{ "screen_name" : "sugbuhills" }
{ "screen_name" : "CheyanneLilFace" }
{ "screen_name" : "manny_cabral" }
{ "screen_name" : "davidpasca" }
{ "screen_name" : "terekey" }
{ "screen_name" : "BSPBIKESDOTCOM" }
{ "screen_name" : "sadenshi" }
{ "screen_name" : "GallaghMargaret" }
{ "screen_name" : "caitlinjeaneliz" }
{ "screen_name" : "ClotheslineBC" }
{ "screen_name" : "ArtsVancouver" }
{ "screen_name" : "AngelsAnimlResc" }
{ "screen_name" : "EcoArtsSalon" }
{ "screen_name" : "ScoutFor" }
{ "screen_name" : "VanRelationship" }
{ "screen_name" : "g_delucca" }
{ "screen_name" : "RobinVan" }
{ "screen_name" : "willowswings" }
{ "screen_name" : "IglikaIvanova" }
{ "screen_name" : "leslie_mcguire" }
{ "screen_name" : "ALGUSTOlatinos" }
{ "screen_name" : "TalesofKirkus" }
{ "screen_name" : "claraoyeung" }
{ "screen_name" : "nardwuar" }
{ "screen_name" : "BudgetRACBC" }
{ "screen_name" : "Sail_ByAdera" }
{ "screen_name" : "whatjesswants" }
{ "screen_name" : "hikebiz" }
{ "screen_name" : "rcvan" }
{ "screen_name" : "LeezaUdovenko" }
{ "screen_name" : "IanYeung" }
{ "screen_name" : "PMeisznerGlobal" }
{ "screen_name" : "megburnsdolson" }
{ "screen_name" : "valoreonthepark" }
{ "screen_name" : "Lamarche" }
{ "screen_name" : "StdntSchlBks" }
{ "screen_name" : "ubcgrandprix" }
{ "screen_name" : "KodySocialMedia" }
{ "screen_name" : "jess_pan" }
{ "screen_name" : "jjbetree" }
{ "screen_name" : "zoeyryan" }
{ "screen_name" : "SteveNicklen" }
{ "screen_name" : "cbruntlett" }
{ "screen_name" : "theRealYVR" }
{ "screen_name" : "mir_miller" }
{ "screen_name" : "ellekane" }
{ "screen_name" : "Kath_MacLeod" }
{ "screen_name" : "Galyak" }
{ "screen_name" : "eugenecube" }
{ "screen_name" : "RealtorBenjamin" }
{ "screen_name" : "chrisporcina" }
{ "screen_name" : "MusingUrbanist" }
{ "screen_name" : "HODProductions" }
{ "screen_name" : "fbarza" }
{ "screen_name" : "LynnOsler07" }
{ "screen_name" : "kathryntonelli" }
{ "screen_name" : "dianamlam" }
{ "screen_name" : "VanFFL" }
{ "screen_name" : "LDLondonStation" }
{ "screen_name" : "Allie_Sass" }
{ "screen_name" : "markottewell" }
{ "screen_name" : "LouandLiz" }
{ "screen_name" : "spacingvan" }
{ "screen_name" : "sengsuriya" }
{ "screen_name" : "GumDropsRain" }
{ "screen_name" : "ShawnCEvent" }
{ "screen_name" : "susan_seto" }
{ "screen_name" : "carolinefair" }
{ "screen_name" : "rhodesolutions" }
{ "screen_name" : "maremurray" }
{ "screen_name" : "EmilySChristian" }
{ "screen_name" : "Travisu924" }
{ "screen_name" : "SurreyMarathon" }
{ "screen_name" : "VanBathReno" }
{ "screen_name" : "VantageRealty" }
{ "screen_name" : "Infinitywestern" }
{ "screen_name" : "HOTjobs_Canada" }
{ "screen_name" : "YuriArtibise" }
{ "screen_name" : "Shastav874" }
{ "screen_name" : "megantcampbell" }
{ "screen_name" : "PetrichorBliss" }
{ "screen_name" : "thebbcreative" }
{ "screen_name" : "Viva_Van" }
{ "screen_name" : "Rubika_n" }
{ "screen_name" : "DorothySitek" }
{ "screen_name" : "bahoonie" }
{ "screen_name" : "amarajanssens" }
{ "screen_name" : "j_essim_ac" }
{ "screen_name" : "Ninfad889" }
{ "screen_name" : "AnthemYVR" }
{ "screen_name" : "tisfortransit" }
{ "screen_name" : "Tericac009" }
{ "screen_name" : "barbjustason" }
{ "screen_name" : "TapestrySeniors" }
{ "screen_name" : "KelseySees" }
{ "screen_name" : "caneducation" }
{ "screen_name" : "thehood604" }
{ "screen_name" : "mashomi3" }
{ "screen_name" : "fpsphotograph" }
{ "screen_name" : "CraigJMassey" }
{ "screen_name" : "GDF2007" }
{ "screen_name" : "diyyinah" }
{ "screen_name" : "_MyVancouver_" }
{ "screen_name" : "Torril58" }
{ "screen_name" : "erinUBC" }
{ "screen_name" : "Lori_writes" }
{ "screen_name" : "amanda_panes" }
{ "screen_name" : "elenisentme" }
{ "screen_name" : "ndck69" }
{ "screen_name" : "dukebd2233" }
{ "screen_name" : "glendaollero" }
{ "screen_name" : "mdobrinskaya" }
{ "screen_name" : "KAYAVancouver" }
{ "screen_name" : "owiesgrandma" }
{ "screen_name" : "BCbaydoll" }
{ "screen_name" : "Joshp1786" }
{ "screen_name" : "Naomaq164" }
{ "screen_name" : "Tommyi21" }
{ "screen_name" : "emiliegwalker" }
{ "screen_name" : "cvmevents" }
{ "screen_name" : "suz_OswegoHotel" }
{ "screen_name" : "hunterjmoyes" }
{ "screen_name" : "robnagai" }
{ "screen_name" : "TheGreenMen" }
{ "screen_name" : "NSautomall" }
{ "screen_name" : "nancampbell" }
{ "screen_name" : "SteamPiston76" }
{ "screen_name" : "KenCharko" }
{ "screen_name" : "WayneRacine" }
{ "screen_name" : "NicoleMJanssen" }
{ "screen_name" : "ecoerin99" }
{ "screen_name" : "MonikaRola" }
{ "screen_name" : "jninvan" }
{ "screen_name" : "D4Repurposing" }
{ "screen_name" : "MikeAverbach" }
{ "screen_name" : "GermanBC" }
{ "screen_name" : "sdignos" }
{ "screen_name" : "Doriasalon" }
{ "screen_name" : "karensawa" }
{ "screen_name" : "PrestonMobility" }
{ "screen_name" : "AVancouverBus" }
{ "screen_name" : "VancouvertoSea" }
{ "screen_name" : "annnnik" }
{ "screen_name" : "Stephanie_Ryan" }
{ "screen_name" : "Backyardbuzz" }
{ "screen_name" : "BC_HC" }
{ "screen_name" : "ParksBoardFacts" }
{ "screen_name" : "BrasserieBistro" }
{ "screen_name" : "chuarrr" }
{ "screen_name" : "_alexbuss" }
{ "screen_name" : "VertiThink" }
{ "screen_name" : "MetroHall" }
{ "screen_name" : "PaulaProperties" }
{ "screen_name" : "2011_Challenge" }
{ "screen_name" : "FarahKhurrum" }
{ "screen_name" : "W21Conferences" }
{ "screen_name" : "SFU_Climate" }
{ "screen_name" : "encimadjid" }
{ "screen_name" : "talkingfrog" }
{ "screen_name" : "modo_carcoop" }
{ "screen_name" : "saveyourskinfdn" }
{ "screen_name" : "SparkInVictoria" }
{ "screen_name" : "ChrisVelascoBBA" }
{ "screen_name" : "tomhanger" }
{ "screen_name" : "MayorWatts" }
{ "screen_name" : "BryceTarling" }
{ "screen_name" : "vantransp2040" }
{ "screen_name" : "JENNIQUA" }
{ "screen_name" : "leahevansnz" }
{ "screen_name" : "TrevorLoke" }
{ "screen_name" : "eastvanista" }
{ "screen_name" : "MikeMagee" }
{ "screen_name" : "KimParties" }
{ "screen_name" : "Wendy_Stueck" }
{ "screen_name" : "Jason_E_King" }
{ "screen_name" : "CivicInfo" }
{ "screen_name" : "paulinatin" }
{ "screen_name" : "PairBistro" }
{ "screen_name" : "KarlaNote" }
{ "screen_name" : "cancersocietybc" }
{ "screen_name" : "MissTJ_talks" }
{ "screen_name" : "RaniaHatz" }
{ "screen_name" : "CityStudioVan" }
{ "screen_name" : "MyLoverArlo" }
{ "screen_name" : "sadiemcnair" }
{ "screen_name" : "wesgroup" }
{ "screen_name" : "AndersonProto" }
{ "screen_name" : "marissaCphoto" }
{ "screen_name" : "melissabee_" }
{ "screen_name" : "ErinRennie" }
{ "screen_name" : "innesy" }
{ "screen_name" : "JnettersB" }
{ "screen_name" : "hotVancouver" }
{ "screen_name" : "grncityconv" }
{ "screen_name" : "dylansherlock" }
{ "screen_name" : "iamin_between" }
{ "screen_name" : "brentonwalters" }
{ "screen_name" : "saraljohnston" }
{ "screen_name" : "_hubbub" }
{ "screen_name" : "sammyjgrill" }
{ "screen_name" : "genumark" }
{ "screen_name" : "cuiscenerest" }
{ "screen_name" : "Vote4RinaGill" }
{ "screen_name" : "zannalyons" }
{ "screen_name" : "YouCanFrame" }
{ "screen_name" : "cupacorn" }
{ "screen_name" : "VanMayorsOffice" }
{ "screen_name" : "edwin_tweet" }
{ "screen_name" : "Katrrific" }
{ "screen_name" : "calicultclassic" }
{ "screen_name" : "GrittaniLiving" }
{ "screen_name" : "DowntownCharles" }
{ "screen_name" : "ErikaFinlay" }
{ "screen_name" : "mcguireclinic" }
{ "screen_name" : "lukebalson" }
{ "screen_name" : "UBCLearn" }
{ "screen_name" : "singisking604" }
{ "screen_name" : "stephanie_ip" }
{ "screen_name" : "ICBC_Lawyer" }
{ "screen_name" : "emilysproule" }
{ "screen_name" : "ponymalta" }
{ "screen_name" : "LoveVancouver" }
{ "screen_name" : "2ndtheBest" }
{ "screen_name" : "ArrowsmithGolf" }
{ "screen_name" : "TimWray" }
{ "screen_name" : "leftonlougheed" }
{ "screen_name" : "MilesEmployment" }
{ "screen_name" : "leitamartin" }
{ "screen_name" : "ConcertProp" }
{ "screen_name" : "mikestatten" }
{ "screen_name" : "kermodestudio" }
{ "screen_name" : "reflexp" }
{ "screen_name" : "christine_robb" }
{ "screen_name" : "saskiamorgan" }
{ "screen_name" : "transitmuseum" }
{ "screen_name" : "DaveDDavis" }
{ "screen_name" : "malloryclaire_" }
{ "screen_name" : "RonChunick" }
{ "screen_name" : "Whole_Foods_Man" }
{ "screen_name" : "maserati8989" }
{ "screen_name" : "nelson_chiu" }
{ "screen_name" : "freegeekvan" }
{ "screen_name" : "MichaelYVR" }
{ "screen_name" : "elainee430" }
{ "screen_name" : "Live_4_Tomorrow" }
{ "screen_name" : "RDVancouver" }
{ "screen_name" : "FairmontWF" }
{ "screen_name" : "nome14" }
{ "screen_name" : "CloudPockets" }
{ "screen_name" : "love_nux" }
{ "screen_name" : "bradrichert" }
{ "screen_name" : "vanclassifieds" }
{ "screen_name" : "Demian_R" }
{ "screen_name" : "bikerides" }
{ "screen_name" : "allscenes" }
{ "screen_name" : "angeliquestudio" }
{ "screen_name" : "ArtisanMrkt604" }
{ "screen_name" : "JustinCLKaiser" }
{ "screen_name" : "ngwright" }
{ "screen_name" : "tinawhoo15" }
{ "screen_name" : "ElizJackman" }
{ "screen_name" : "josiepadro" }
{ "screen_name" : "OneRainyWish" }
{ "screen_name" : "CostlessExpress" }
{ "screen_name" : "eastvanbran" }
{ "screen_name" : "TroutLakeCC" }
{ "screen_name" : "CoLABeration" }
{ "screen_name" : "REFEDBCDOTCOM" }
{ "screen_name" : "Y4CJN" }
{ "screen_name" : "coquitlamcentre" }
{ "screen_name" : "SFULipDub" }
{ "screen_name" : "ShelleyDmann" }
{ "screen_name" : "vancityprofile" }
{ "screen_name" : "Ashley_Realtor" }
{ "screen_name" : "jitsulab" }
{ "screen_name" : "MTpleasant_Van" }
{ "screen_name" : "megskim1126" }
{ "screen_name" : "vancouverme" }
{ "screen_name" : "greenwood_annie" }
{ "screen_name" : "NHArtsInc" }
{ "screen_name" : "br_webb" }
{ "screen_name" : "RobertsAnnex" }
{ "screen_name" : "VehicleSalesBC" }
{ "screen_name" : "CelebOfLight" }
{ "screen_name" : "vaninst" }
{ "screen_name" : "vocalvancouver" }
{ "screen_name" : "leahebae" }
{ "screen_name" : "TheWolfAndHound" }
{ "screen_name" : "DailySaverCan" }
{ "screen_name" : "plifinancial" }
{ "screen_name" : "Allegra_ca" }
{ "screen_name" : "MissLKP87" }
{ "screen_name" : "TKChocolate" }
{ "screen_name" : "natallulah" }
{ "screen_name" : "nealjennings" }
{ "screen_name" : "vancityjames" }
{ "screen_name" : "robinmasashi" }
{ "screen_name" : "jjvanruyven" }
{ "screen_name" : "YasmineMoulin" }
{ "screen_name" : "GinaKnowsBest" }
{ "screen_name" : "mimischap" }
{ "screen_name" : "Lanewayhousing" }
{ "screen_name" : "MayorGregor" }
{ "screen_name" : "Chatterbox1000" }
{ "screen_name" : "markowsky" }
{ "screen_name" : "Navrita14" }
{ "screen_name" : "offthetacowagon" }
{ "screen_name" : "Ronald_Sears_93" }
{ "screen_name" : "Mall4Mobile" }
{ "screen_name" : "EMBERSGR" }
{ "screen_name" : "lucyhyslop" }
{ "screen_name" : "411Regan" }
{ "screen_name" : "InaBits" }
{ "screen_name" : "PMConcerts" }
{ "screen_name" : "HomeBilliards" }
{ "screen_name" : "LindsaySommersU" }
{ "screen_name" : "viaarchitecture" }
{ "screen_name" : "juliemjenkins" }
{ "screen_name" : "GERBER_Realtor" }
{ "screen_name" : "cyclechickfun" }
{ "screen_name" : "GeoChangeFNDN" }
{ "screen_name" : "merlin12" }
{ "screen_name" : "HollyburnPpty" }
{ "screen_name" : "kisielk" }
{ "screen_name" : "WorkingCMNS" }
{ "screen_name" : "Fangy69" }
{ "screen_name" : "AnnaMaeAbia" }
{ "screen_name" : "tanyapazzy" }
{ "screen_name" : "myinsuranceline" }
{ "screen_name" : "driven16" }
{ "screen_name" : "rabeaton" }
{ "screen_name" : "paigemp" }
{ "screen_name" : "debrandservices" }
{ "screen_name" : "glowconsult" }
{ "screen_name" : "sunspiritwv" }
{ "screen_name" : "NorthVanCityLib" }
{ "screen_name" : "TheOtherCorp" }
{ "screen_name" : "raincityhsg" }
{ "screen_name" : "alleycat8675309" }
{ "screen_name" : "Vertopia" }
{ "screen_name" : "bardabus" }
{ "screen_name" : "BGIslander" }
{ "screen_name" : "seanleslie980" }
{ "screen_name" : "Nory_RareIndigo" }
{ "screen_name" : "kirahiwa" }
{ "screen_name" : "mohchelali" }
{ "screen_name" : "citizenpen" }
{ "screen_name" : "shanikjing" }
{ "screen_name" : "EcoCollectivist" }
{ "screen_name" : "KillarneyCC" }
{ "screen_name" : "WhiteRock_BC" }
{ "screen_name" : "ATutoringClub" }
{ "screen_name" : "nsoundhearing" }
{ "screen_name" : "westvanbcspca" }
{ "screen_name" : "amyakirkham" }
{ "screen_name" : "InsertThotHere" }
{ "screen_name" : "KellyLeeFamous" }
{ "screen_name" : "Craig_Hunt_" }
{ "screen_name" : "msuica" }
{ "screen_name" : "pacificcarrent" }
{ "screen_name" : "m4mainia" }
{ "screen_name" : "InspireYouthCon" }
{ "screen_name" : "TheMartlet" }
{ "screen_name" : "CycleBCVancity" }
{ "screen_name" : "whereiskp" }
{ "screen_name" : "housecallsinc" }
{ "screen_name" : "IranEduSoc" }
{ "screen_name" : "kerrzan" }
{ "screen_name" : "ElementsSociety" }
{ "screen_name" : "irisdias" }
{ "screen_name" : "vancouverautos" }
{ "screen_name" : "andrea_malo" }
{ "screen_name" : "thebusloop" }
{ "screen_name" : "heather_604" }
{ "screen_name" : "surviveinvan" }
{ "screen_name" : "REELCASCADIA" }
{ "screen_name" : "carvertising" }
{ "screen_name" : "ToryLineDuJour" }
{ "screen_name" : "americanfab" }
{ "screen_name" : "stuccoVancouver" }
{ "screen_name" : "sehmer" }
{ "screen_name" : "ifwhiterock" }
{ "screen_name" : "lafalott" }
{ "screen_name" : "thomaspbrennan" }
{ "screen_name" : "johnsonbenny" }
{ "screen_name" : "SalientEvents" }
{ "screen_name" : "cheapcouver" }
{ "screen_name" : "vangarden" }
{ "screen_name" : "jim_balakshin" }
{ "screen_name" : "J_Dolson" }
{ "screen_name" : "Waldorf_TikiBar" }
{ "screen_name" : "VSB39" }
{ "screen_name" : "ThePRLife" }
{ "screen_name" : "square1paving" }
{ "screen_name" : "lmbann" }
{ "screen_name" : "ICS_Events" }
{ "screen_name" : "cameronsgray" }
{ "screen_name" : "zen_ByAdera" }
{ "screen_name" : "aprilemoine" }
{ "screen_name" : "Maplewood_Farm" }
{ "screen_name" : "ArtsySportsy" }
{ "screen_name" : "omg_productions" }
{ "screen_name" : "ayjagolder" }
{ "screen_name" : "CapUBusiness" }
{ "screen_name" : "KeystoneEnv" }
{ "screen_name" : "TBejaGlobal" }
{ "screen_name" : "BCConnoisseur" }
{ "screen_name" : "five15design" }
{ "screen_name" : "OneWellness" }
{ "screen_name" : "maritaluk" }
{ "screen_name" : "OpenCascadia" }
{ "screen_name" : "machado_pm" }
{ "screen_name" : "ReeveConsulting" }
{ "screen_name" : "mapleridgealex" }
{ "screen_name" : "yasuhikoogushi" }
{ "screen_name" : "EssentialCity" }
{ "screen_name" : "contestpatti" }
{ "screen_name" : "ggrraccee" }
{ "screen_name" : "teririch" }
{ "screen_name" : "myhattricks" }
{ "screen_name" : "MarybethWelty" }
{ "screen_name" : "GVZooChat" }
{ "screen_name" : "Knittingrid" }
{ "screen_name" : "EnviroVotersBC" }
{ "screen_name" : "taxelsson" }
{ "screen_name" : "jenn_wint" }
{ "screen_name" : "BCPSEA" }
{ "screen_name" : "OpreetKang" }
{ "screen_name" : "hobs" }
{ "screen_name" : "SportMedBC" }
{ "screen_name" : "marghernandez_" }
{ "screen_name" : "thepubcrawls" }
{ "screen_name" : "theTimDavidson" }
{ "screen_name" : "ratemybuilderca" }
{ "screen_name" : "GregorsGreenBK" }
{ "screen_name" : "Paragonkelowna" }
{ "screen_name" : "dqojkerrisdale" }
{ "screen_name" : "TamsynBurgmann" }
{ "screen_name" : "vanchc" }
{ "screen_name" : "kirky_D" }
{ "screen_name" : "VanWorldMusic" }
{ "screen_name" : "PrimeEarth" }
{ "screen_name" : "solsticeimage" }
{ "screen_name" : "vitalityclinic" }
{ "screen_name" : "VedranDj" }
{ "screen_name" : "CathedralLodge" }
{ "screen_name" : "itswictor" }
{ "screen_name" : "stephaniercw" }
{ "screen_name" : "WayneRadford" }
{ "screen_name" : "AIOM_2012" }
{ "screen_name" : "IslandRail" }
{ "screen_name" : "williewox" }
{ "screen_name" : "Whut2do" }
{ "screen_name" : "the_bruise" }
{ "screen_name" : "hollywood604" }
{ "screen_name" : "brocknhunter" }
{ "screen_name" : "MarnieMcG" }
{ "screen_name" : "PK_Media" }
{ "screen_name" : "StanleyPkEcoSoc" }
{ "screen_name" : "brittanywong" }
{ "screen_name" : "sipforchange" }
{ "screen_name" : "louisebrealtor" }
{ "screen_name" : "KaitlinEShields" }
{ "screen_name" : "PD_plumbing" }
{ "screen_name" : "WEDDINGSinGVRD" }
{ "screen_name" : "WRRealty" }
{ "screen_name" : "WhiteRockShops" }
{ "screen_name" : "AndrewChinny" }
{ "screen_name" : "Surrey_Mechanic" }
{ "screen_name" : "soulD3LAY" }
{ "screen_name" : "TomasWilliamsA" }
{ "screen_name" : "WRWebDesign" }
{ "screen_name" : "WhiteRockOnline" }
{ "screen_name" : "LAWinVANCOUVER" }
{ "screen_name" : "Jess_Ik_a" }
{ "screen_name" : "WhiteRockHealth" }
{ "screen_name" : "OrcaCedarbough" }
{ "screen_name" : "Surrey_Shopping" }
{ "screen_name" : "BeautyNight" }
{ "screen_name" : "BC_Skiing" }
{ "screen_name" : "keen9000" }
{ "screen_name" : "paulnixey" }
{ "screen_name" : "nfaz88" }
{ "screen_name" : "StrucEngr" }
{ "screen_name" : "WhiteRockCoupon" }
{ "screen_name" : "JEEPSKINGBC" }
{ "screen_name" : "SpringLiving" }
{ "screen_name" : "martinmacmahon" }
{ "screen_name" : "VanLearningCity" }
{ "screen_name" : "VancouverBMW" }
{ "screen_name" : "WestPrinciples" }
{ "screen_name" : "KristiFurtney" }
{ "screen_name" : "bchydro" }
{ "screen_name" : "mpibcchapter" }
{ "screen_name" : "SustainableSFU" }
{ "screen_name" : "MarishaDevoin" }
{ "screen_name" : "teachingtammy" }
{ "screen_name" : "p8n8lop8" }
{ "screen_name" : "goto11" }
{ "screen_name" : "cesago" }
{ "screen_name" : "Lordsshoes" }
{ "screen_name" : "wpgadotca" }
{ "screen_name" : "AndreaCarol1na" }
{ "screen_name" : "amandagoesgreen" }
{ "screen_name" : "kasimirkish" }
{ "screen_name" : "illibby" }
{ "screen_name" : "SauderNetImpact" }
{ "screen_name" : "HerraincoBrand" }
{ "screen_name" : "braedencaley" }
{ "screen_name" : "cthorbes" }
{ "screen_name" : "SFUDialogue" }
{ "screen_name" : "LaPir0" }
{ "screen_name" : "GlobalBC" }
{ "screen_name" : "jleighharder" }
{ "screen_name" : "SESatCapU" }
{ "screen_name" : "drumweaver" }
{ "screen_name" : "ACTCanada" }
{ "screen_name" : "littleagent" }
{ "screen_name" : "24HourRelayBC" }
{ "screen_name" : "OfficialVCBF" }
{ "screen_name" : "GastownPP" }
{ "screen_name" : "colinbriggs" }
{ "screen_name" : "BC_SPCA" }
{ "screen_name" : "HyattVancouver" }
{ "screen_name" : "Splitzgrill" }
{ "screen_name" : "SandyYoung3" }
{ "screen_name" : "stoodles" }
{ "screen_name" : "GobiNEWS" }
{ "screen_name" : "NicoleGrima" }
{ "screen_name" : "space_cadet00" }
{ "screen_name" : "MichaelAynsley" }
{ "screen_name" : "kreaburn" }
{ "screen_name" : "iheartcommuting" }
{ "screen_name" : "christianpmills" }
{ "screen_name" : "ubcnews" }
{ "screen_name" : "EFIVANCOUVER" }
{ "screen_name" : "DubbulDee" }
{ "screen_name" : "NegarMojtahedi" }
{ "screen_name" : "NatureTrustofBC" }
{ "screen_name" : "EndoraFan" }
{ "screen_name" : "MCMPDailies" }
{ "screen_name" : "jeanlehtinen" }
{ "screen_name" : "AdamHyslop" }
{ "screen_name" : "beluggie" }
{ "screen_name" : "larang" }
{ "screen_name" : "kathyyanli" }
{ "screen_name" : "yasmin_a" }
{ "screen_name" : "pointblank604" }
{ "screen_name" : "CoopCulture" }
{ "screen_name" : "BCRobyn" }
{ "screen_name" : "rangichangi" }
{ "screen_name" : "JunkCarTowing" }
{ "screen_name" : "clarke_team" }
{ "screen_name" : "JordanTSimmons" }
{ "screen_name" : "ni_kol" }
{ "screen_name" : "YWVanWODA" }
{ "screen_name" : "AgapeConcierge" }
{ "screen_name" : "Robtleitch" }
{ "screen_name" : "VancouverSun" }
{ "screen_name" : "theBrassAction" }
{ "screen_name" : "saucyjocie" }
{ "screen_name" : "monchichi___" }
{ "screen_name" : "fshamji" }
{ "screen_name" : "amyculture" }
{ "screen_name" : "lordtwig" }
{ "screen_name" : "chrismulvena" }
{ "screen_name" : "ThomasFMoore" }
{ "screen_name" : "mpatricklee" }
{ "screen_name" : "alissakeiko" }
{ "screen_name" : "The_GrandLife" }
{ "screen_name" : "99Vancouver" }
{ "screen_name" : "paulbaluch" }
{ "screen_name" : "ceiarchitecture" }
{ "screen_name" : "SpokesVancouver" }
{ "screen_name" : "YourCityHeating" }
{ "screen_name" : "BCLesClefsdOr" }
{ "screen_name" : "Jenn_A_88" }
{ "screen_name" : "Projects604" }
{ "screen_name" : "kitslove" }
{ "screen_name" : "lindsay_noyes" }
{ "screen_name" : "SBIA_GreenZone" }
{ "screen_name" : "LynnCanyonPark" }
{ "screen_name" : "BigTimeTours" }
{ "screen_name" : "leo_ng803" }
{ "screen_name" : "wongmon" }
{ "screen_name" : "CasinoEdgewater" }
{ "screen_name" : "deedhaliwal" }
{ "screen_name" : "carolynreardon" }
{ "screen_name" : "willkidsmusic" }
{ "screen_name" : "saragraves" }
{ "screen_name" : "vancouver125" }
{ "screen_name" : "ClarksAV" }
{ "screen_name" : "krisetches" }
{ "screen_name" : "scottthran" }
{ "screen_name" : "CoupzVancouver" }
{ "screen_name" : "MCI_Vancouver" }
{ "screen_name" : "EthosStrategy" }
{ "screen_name" : "LorienHenson" }
{ "screen_name" : "FalseCreekFerry" }
{ "screen_name" : "m_narula" }
{ "screen_name" : "me_owth" }
{ "screen_name" : "DUBOLLP" }
{ "screen_name" : "ea_p" }
{ "screen_name" : "PowerPlantVan" }
{ "screen_name" : "LimeLightEvents" }
{ "screen_name" : "dwmah" }
{ "screen_name" : "ItsRyanClayton" }
{ "screen_name" : "UBC_RMS" }
{ "screen_name" : "OnWays2Pleasure" }
{ "screen_name" : "vanfleamarket" }
{ "screen_name" : "PJWDavidson" }
{ "screen_name" : "petermacrae" }
{ "screen_name" : "vancouverkelvin" }
{ "screen_name" : "jahutka" }
{ "screen_name" : "CdnGamesConf" }
{ "screen_name" : "Museumofvan" }
{ "screen_name" : "kootenayborn" }
{ "screen_name" : "BC_VOTE" }
{ "screen_name" : "vitaminSH" }
{ "screen_name" : "hannerl" }
{ "screen_name" : "InventFuture" }
{ "screen_name" : "olusha" }
{ "screen_name" : "nicksartore" }
{ "screen_name" : "TravelodgeVic" }
{ "screen_name" : "CKNWWeekendNews" }
{ "screen_name" : "MetropolitanCC" }
{ "screen_name" : "DueckGMDowntown" }
{ "screen_name" : "Roselle_E" }
{ "screen_name" : "birdiehamilton" }
{ "screen_name" : "JimmyLeeLam" }
{ "screen_name" : "GreenVanpool" }
{ "screen_name" : "Hanstastik" }
{ "screen_name" : "TheRealDeanHill" }
{ "screen_name" : "thiscitylifeyvr" }
{ "screen_name" : "Brookland_condo" }
{ "screen_name" : "ConsumerProBC" }
{ "screen_name" : "katiejeanes" }
{ "screen_name" : "hornjohnhorn" }
{ "screen_name" : "sefalsecreek" }
{ "screen_name" : "murphybarb" }
{ "screen_name" : "denisepraill" }
{ "screen_name" : "RalphsRadio" }
{ "screen_name" : "maratooney" }
{ "screen_name" : "ShiatsuQuay" }
{ "screen_name" : "CaseIT" }
{ "screen_name" : "ptorrevillas" }
{ "screen_name" : "NateOrganic" }
{ "screen_name" : "charterbuslines" }
{ "screen_name" : "_lizcraig" }
{ "screen_name" : "RetainMyTalents" }
{ "screen_name" : "ParkBoard" }
{ "screen_name" : "FootSolutionsBC" }
{ "screen_name" : "BeeVancity" }
{ "screen_name" : "buildingtester" }
{ "screen_name" : "dbutton" }
{ "screen_name" : "UBCRobsonSquare" }
{ "screen_name" : "WolfgangPainter" }
{ "screen_name" : "joezaccaria" }
{ "screen_name" : "stephengillis" }
{ "screen_name" : "alisachoi" }
{ "screen_name" : "jeff_w32" }
{ "screen_name" : "nlamontagne" }
{ "screen_name" : "ivancouverite" }
{ "screen_name" : "emmapydee" }
{ "screen_name" : "thinkcity" }
{ "screen_name" : "StreamofDreams" }
{ "screen_name" : "AimeeRita" }
{ "screen_name" : "OrionIrvine" }
{ "screen_name" : "Complainerea" }
{ "screen_name" : "VanConstruction" }
{ "screen_name" : "paulcip" }
{ "screen_name" : "snicoles" }
{ "screen_name" : "carbontalks" }
{ "screen_name" : "cdnkitcat" }
{ "screen_name" : "greenglobetips" }
{ "screen_name" : "ecojackiejo" }
{ "screen_name" : "islandbritt" }
{ "screen_name" : "UrbanSnapshot" }
{ "screen_name" : "VancouverJock" }
{ "screen_name" : "CiTRradio" }
{ "screen_name" : "_conniewan" }
{ "screen_name" : "saltspringsspa" }
{ "screen_name" : "Vancouver_Adam" }
{ "screen_name" : "WorkSafeBC" }
{ "screen_name" : "kalyeena" }
{ "screen_name" : "ABPBC" }
{ "screen_name" : "soundtherapyrad" }
{ "screen_name" : "FreyjaRealEstat" }
{ "screen_name" : "bluegreenclean" }
{ "screen_name" : "lee_crl" }
{ "screen_name" : "ICareSandra" }
{ "screen_name" : "BCVCPeaceArch" }
{ "screen_name" : "Saferway" }
{ "screen_name" : "steph_chua" }
{ "screen_name" : "VancityBuzz" }
{ "screen_name" : "BrendaLindal" }
{ "screen_name" : "InkTonerDepot" }
{ "screen_name" : "bifnaked" }
{ "screen_name" : "EPIC_Expo" }
{ "screen_name" : "dhollick" }
{ "screen_name" : "VancouversDeals" }
{ "screen_name" : "BestHomesBC" }
{ "screen_name" : "randomcouture" }
{ "screen_name" : "SamsungHTC" }
{ "screen_name" : "Vasensa_YVR" }
{ "screen_name" : "penumbradesign" }
{ "screen_name" : "SusanThomas2011" }
{ "screen_name" : "ericafromcanada" }
{ "screen_name" : "TomTheCarGuy" }
{ "screen_name" : "VanLookout" }
{ "screen_name" : "janeter_" }
{ "screen_name" : "tantwy" }
{ "screen_name" : "KitsChamber" }
{ "screen_name" : "Dirt_Merchant" }
{ "screen_name" : "TownShift" }
{ "screen_name" : "CivicJobs" }
{ "screen_name" : "justjoice" }
{ "screen_name" : "pembina" }
{ "screen_name" : "missrachelha" }
{ "screen_name" : "masalapuri" }
{ "screen_name" : "Rezvia" }
{ "screen_name" : "BCFerries" }
{ "screen_name" : "marpolevillage" }
{ "screen_name" : "PrimusTutors" }
{ "screen_name" : "UFWcoquitlam" }
{ "screen_name" : "VancouverSEM" }
{ "screen_name" : "unionwill" }
{ "screen_name" : "JournalismJunki" }
{ "screen_name" : "SouthGranville" }
{ "screen_name" : "FreeForAllEvent" }
{ "screen_name" : "RecyclingBC" }
{ "screen_name" : "whalleylegion" }
{ "screen_name" : "KaylaNeville" }
{ "screen_name" : "PJCavan" }
{ "screen_name" : "StrathconaBIA" }
{ "screen_name" : "jehnbenoit" }
{ "screen_name" : "CommsLoft" }
{ "screen_name" : "BCBabs2010" }
{ "screen_name" : "darahhansen" }
{ "screen_name" : "cynthiawildman" }
{ "screen_name" : "CLICK4kids" }
{ "screen_name" : "villageandco" }
{ "screen_name" : "NVanDistrict" }
{ "screen_name" : "yvrhealthfair" }
{ "screen_name" : "TheChapels" }
{ "screen_name" : "chriswalts" }
{ "screen_name" : "mjgalvani" }
{ "screen_name" : "NaomiDevine" }
{ "screen_name" : "Naoibh" }
{ "screen_name" : "carnutcanada" }
{ "screen_name" : "mikekushnir" }
{ "screen_name" : "vancity_vixen" }
{ "screen_name" : "sustainable_CJ" }
{ "screen_name" : "werabc" }
{ "screen_name" : "dogwoodbc" }
{ "screen_name" : "YYoga" }
{ "screen_name" : "BCClassifieds" }
{ "screen_name" : "iContractWork" }
{ "screen_name" : "tanyashum" }
{ "screen_name" : "LyleIsbister" }
{ "screen_name" : "staceandchase" }
{ "screen_name" : "JoshVanBC" }
{ "screen_name" : "AvrgeJoeCyclist" }
{ "screen_name" : "amandawacky" }
{ "screen_name" : "chefnextdoorca" }
{ "screen_name" : "kidsvancouver" }
{ "screen_name" : "MrDance" }
{ "screen_name" : "mrfordx" }
{ "screen_name" : "krystlealarcon" }
{ "screen_name" : "thegooddrive" }
{ "screen_name" : "ehilchey" }
{ "screen_name" : "Karly_GreenP" }
{ "screen_name" : "CivicScene" }
{ "screen_name" : "SFUugsid" }
{ "screen_name" : "pulseenergy" }
{ "screen_name" : "brodiesovereign" }
{ "screen_name" : "BurkeMtnNats" }
{ "screen_name" : "BitaVorell" }
{ "screen_name" : "ULIBC" }
{ "screen_name" : "NSVending" }
{ "screen_name" : "MajorlyMarketng" }
{ "screen_name" : "CDA_Vancouver" }
{ "screen_name" : "raulpacheco" }
{ "screen_name" : "wildernews" }
{ "screen_name" : "EmbersStaffing" }
{ "screen_name" : "testdrivesmart" }
{ "screen_name" : "LokangoVBC" }
{ "screen_name" : "PortMetroVan" }
{ "screen_name" : "UrbanTreefrog" }
{ "screen_name" : "CraigRMcCulloch" }
{ "screen_name" : "LandisHotel" }
{ "screen_name" : "BoardofChange" }
{ "screen_name" : "dorothygrant" }
{ "screen_name" : "ClaudiaAlan" }
{ "screen_name" : "smileshigh" }
{ "screen_name" : "saramelodyy" }
{ "screen_name" : "VanBikeShow" }
{ "screen_name" : "Simon_Kear" }
{ "screen_name" : "Sierra_BC" }
{ "screen_name" : "Jestferlaffs" }
{ "screen_name" : "FreePublicTrans" }
{ "screen_name" : "reporteremma" }
{ "screen_name" : "Greg__Mitchell" }
{ "screen_name" : "Cornerstone_" }
{ "screen_name" : "AryalR" }
{ "screen_name" : "veggyblue" }
{ "screen_name" : "roxannestp" }
{ "screen_name" : "kierankobitz" }
{ "screen_name" : "PowerSmartBC" }
{ "screen_name" : "SUCCESSCanada" }
{ "screen_name" : "emilyreports" }
{ "screen_name" : "PaulC14" }
{ "screen_name" : "LeannaPR" }
{ "screen_name" : "matsuma" }
{ "screen_name" : "alwaysRL" }
{ "screen_name" : "StephenIrving" }
{ "screen_name" : "iAmitKhanna" }
{ "screen_name" : "LavishLiquid" }
{ "screen_name" : "wildcablecanada" }
{ "screen_name" : "maailiving" }
{ "screen_name" : "MeghanRadomske" }
{ "screen_name" : "Ismerelda" }
{ "screen_name" : "Ghost_TrainYVR" }
{ "screen_name" : "j_nice" }
{ "screen_name" : "jhartlo" }
{ "screen_name" : "UBC_CareerServ" }
{ "screen_name" : "rbrtwhite" }
{ "screen_name" : "ianaustin007" }
{ "screen_name" : "BCSEA" }
{ "screen_name" : "annaandaaron" }
{ "screen_name" : "itcaughtmyeye" }
{ "screen_name" : "BrentHogarth" }
{ "screen_name" : "GetSocialCity" }
{ "screen_name" : "mrkaboomcon" }
{ "screen_name" : "roguewetbar" }
{ "screen_name" : "VanConventions" }
{ "screen_name" : "pre_planner" }
{ "screen_name" : "ExoticFurnish" }
{ "screen_name" : "renodiva" }
{ "screen_name" : "peracollege" }
{ "screen_name" : "TravellerCanada" }
{ "screen_name" : "EBOOSTCANADA" }
{ "screen_name" : "sribeiro" }
{ "screen_name" : "hierichmond" }
{ "screen_name" : "slipp3ryf1sh" }
{ "screen_name" : "Harkirat77" }
{ "screen_name" : "Sassy__M" }
{ "screen_name" : "SerenaHartl" }
{ "screen_name" : "paulreniers" }
{ "screen_name" : "KevinSkrepnek" }
{ "screen_name" : "hobsonlin" }
{ "screen_name" : "VolunteerRmd" }
{ "screen_name" : "handsintheearth" }
{ "screen_name" : "rstrpo" }
{ "screen_name" : "ubcrec" }
{ "screen_name" : "luluada" }
{ "screen_name" : "gnonni" }
{ "screen_name" : "VinceSharma" }
{ "screen_name" : "alfredjulian" }
{ "screen_name" : "bardonthebeach" }
{ "screen_name" : "michelleyuen" }
{ "screen_name" : "MountainViewCem" }
{ "screen_name" : "TakeaHikeFdn" }
{ "screen_name" : "ChristopherTait" }
{ "screen_name" : "GoSouthlands" }
{ "screen_name" : "kharbinson" }
{ "screen_name" : "ashley_3101" }
{ "screen_name" : "VanChristmas" }
{ "screen_name" : "METRINGlow" }
{ "screen_name" : "pureplumbing" }
{ "screen_name" : "jessicup84" }
{ "screen_name" : "kunstudios" }
{ "screen_name" : "BradenMacD" }
{ "screen_name" : "lorene1voice" }
{ "screen_name" : "Rob_MacDougall" }
{ "screen_name" : "SteamworksPub" }
{ "screen_name" : "HighendLimo" }
{ "screen_name" : "jpiwowar" }
{ "screen_name" : "UrbBlurb" }
{ "screen_name" : "nineoclockgun" }
{ "screen_name" : "fitnessali" }
{ "screen_name" : "SustainUBC" }
{ "screen_name" : "VanCityChiro" }
{ "screen_name" : "srobarts" }
{ "screen_name" : "CityChaseVan" }
{ "screen_name" : "MStarInc" }
{ "screen_name" : "VancityFunGal" }
{ "screen_name" : "CBRProducts" }
{ "screen_name" : "BCRFA" }
{ "screen_name" : "chrisfischer247" }
{ "screen_name" : "RobertMThompson" }
{ "screen_name" : "bijbij" }
{ "screen_name" : "StopUBCanimalre" }
{ "screen_name" : "mydoctorgreen" }
{ "screen_name" : "bellecoeur" }
{ "screen_name" : "FairTradeVan" }
{ "screen_name" : "skyhighballoons" }
{ "screen_name" : "vantagepnt" }
{ "screen_name" : "TheGreenwaybc" }
{ "screen_name" : "alyssa_jayne" }
{ "screen_name" : "VIApasteup" }
{ "screen_name" : "kijomica" }
{ "screen_name" : "saynotoboxes" }
{ "screen_name" : "TravellersDeck" }
{ "screen_name" : "monsieur_mac" }
{ "screen_name" : "ErinLoxam" }
{ "screen_name" : "onewetfoot" }
{ "screen_name" : "Mr_Stash" }
{ "screen_name" : "KidsUpFrontVan" }
{ "screen_name" : "Jeff_Hodson" }
{ "screen_name" : "barkerjacob" }
{ "screen_name" : "onjana" }
{ "screen_name" : "cecepoint" }
{ "screen_name" : "RapidexMoving" }
{ "screen_name" : "samkoopman" }
{ "screen_name" : "RoundhouseCC" }
{ "screen_name" : "furtney" }
{ "screen_name" : "Mt_Seymour" }
{ "screen_name" : "GenesaGreening" }
{ "screen_name" : "capsuspbridge" }
{ "screen_name" : "K8Best" }
{ "screen_name" : "angelfclemente" }
{ "screen_name" : "BottlelessVAN" }
{ "screen_name" : "bccla" }
{ "screen_name" : "pedersencandice" }
{ "screen_name" : "bccycle" }
{ "screen_name" : "tlmarshall65" }
{ "screen_name" : "GE_Canada" }
{ "screen_name" : "romanapizza" }
{ "screen_name" : "BikingToWork" }
{ "screen_name" : "G0Championships" }
{ "screen_name" : "prov_valleygirl" }
{ "screen_name" : "clangmuir" }
{ "screen_name" : "BCLions" }
{ "screen_name" : "wimp_pop" }
{ "screen_name" : "VFVitalSigns" }
{ "screen_name" : "LombardiMike" }
{ "screen_name" : "VtheChan" }
{ "screen_name" : "EvergreenSP" }
{ "screen_name" : "Keri_Adams" }
{ "screen_name" : "jackermann" }
{ "screen_name" : "sthomas10" }
{ "screen_name" : "trevormacinnis" }
{ "screen_name" : "ksalchner" }
{ "screen_name" : "FairmontVan" }
{ "screen_name" : "wellnesscollege" }
{ "screen_name" : "ActivistSmables" }
{ "screen_name" : "sarahblyth" }
{ "screen_name" : "ZipcarVancouver" }
{ "screen_name" : "nstefenelli" }
{ "screen_name" : "VCCKK" }
{ "screen_name" : "BCrideshareweek" }
{ "screen_name" : "jlevis" }
{ "screen_name" : "MSBikeToursBC" }
{ "screen_name" : "eventidetours" }
{ "screen_name" : "danigirl333" }
{ "screen_name" : "TIC_2011" }
{ "screen_name" : "ThePartyBazaar" }
{ "screen_name" : "devinefitness1" }
{ "screen_name" : "frankluba" }
{ "screen_name" : "armstrongkim" }
{ "screen_name" : "CSpacePilates" }
{ "screen_name" : "BTArchitects" }
{ "screen_name" : "TicketsTonight" }
{ "screen_name" : "SunCivicLee" }
{ "screen_name" : "mfestvan" }
{ "screen_name" : "CaitlinLH" }
{ "screen_name" : "AspenClean" }
{ "screen_name" : "WestVanRec" }
{ "screen_name" : "bella_b" }
{ "screen_name" : "katiemercer" }
{ "screen_name" : "pawsforacause" }
{ "screen_name" : "roofvancouver" }
{ "screen_name" : "asgibbs" }
{ "screen_name" : "DropZoneVAN" }
{ "screen_name" : "MetroVanCycle" }
{ "screen_name" : "bcplace" }
{ "screen_name" : "NANDO_PZ" }
{ "screen_name" : "Vancity_FC" }
{ "screen_name" : "godfreyHobbs" }
{ "screen_name" : "causecomms" }
{ "screen_name" : "dtsurreybia" }
{ "screen_name" : "LauraBaziuk980" }
{ "screen_name" : "diamondisinger" }
{ "screen_name" : "AmyBeeman" }
{ "screen_name" : "News1130Shane" }
{ "screen_name" : "smirks4local" }
{ "screen_name" : "MetropolisatMet" }
{ "screen_name" : "TheUPSStore209" }
{ "screen_name" : "michgordonlive" }
{ "screen_name" : "EncorpPacific" }
{ "screen_name" : "thecarcoop" }
{ "screen_name" : "TeamHappyPlanet" }
{ "screen_name" : "roncann" }
{ "screen_name" : "technosmirks" }
{ "screen_name" : "jonathanxcote" }
{ "screen_name" : "stodmyk" }
{ "screen_name" : "tesskitchen" }
{ "screen_name" : "bat_mmx" }
{ "screen_name" : "leonhawkins" }
{ "screen_name" : "perkinswill_VAN" }
{ "screen_name" : "wlouie" }
{ "screen_name" : "seaforth100" }
{ "screen_name" : "lululash" }
{ "screen_name" : "FuFuDoggy" }
{ "screen_name" : "jennychia" }
{ "screen_name" : "SWEETCHERUBIM" }
{ "screen_name" : "thestatelyhome" }
{ "screen_name" : "NSBikeGearSwap" }
{ "screen_name" : "tablefor604" }
{ "screen_name" : "CC_Vancouver" }
{ "screen_name" : "EdKanna" }
{ "screen_name" : "kmyles" }
{ "screen_name" : "anne_mcc" }
{ "screen_name" : "karenflamenco" }
{ "screen_name" : "SukhdipGill" }
{ "screen_name" : "canadademocrats" }
{ "screen_name" : "MumOfThreeBC" }
{ "screen_name" : "jmtoriel" }
{ "screen_name" : "scott_vpsn" }
{ "screen_name" : "RichardChu_BIV" }
{ "screen_name" : "joshworkman" }
{ "screen_name" : "kikivarg" }
{ "screen_name" : "vitalitymarket" }
{ "screen_name" : "AirCareBC" }
{ "screen_name" : "kimpalmero" }
{ "screen_name" : "LD_Robson" }
{ "screen_name" : "JJsplumbing" }
{ "screen_name" : "Anna_Lilly" }
{ "screen_name" : "capademusic" }
{ "screen_name" : "BCScrapIt" }
{ "screen_name" : "starlimousine" }
{ "screen_name" : "CanadaPlace" }
{ "screen_name" : "AngusOneLtd" }
{ "screen_name" : "UrbanDryad" }
{ "screen_name" : "smartfilms" }
{ "screen_name" : "thomsenerin" }
{ "screen_name" : "MurrickInsBC" }
{ "screen_name" : "SteamWhistle" }
{ "screen_name" : "greenbumbum" }
{ "screen_name" : "VancouverView" }
{ "screen_name" : "RyanCompany" }
{ "screen_name" : "raincoaster" }
{ "screen_name" : "GotMyCartridge" }
{ "screen_name" : "derekschlereth" }
{ "screen_name" : "sioface" }
{ "screen_name" : "JoBlive" }
{ "screen_name" : "HotshopIdeas" }
{ "screen_name" : "diw45" }
{ "screen_name" : "TintCentre" }
{ "screen_name" : "DuaneBurnett" }
{ "screen_name" : "jenbarron" }
{ "screen_name" : "paulie_pocket" }
{ "screen_name" : "WDCG_YMCA" }
{ "screen_name" : "theboatinglife" }
{ "screen_name" : "TheBicycleValet" }
{ "screen_name" : "Recruiter_Devi" }
{ "screen_name" : "CotP_DoM" }
{ "screen_name" : "acrotech" }
{ "screen_name" : "Leonashanana" }
{ "screen_name" : "BESTmobility" }
{ "screen_name" : "julielyngendron" }
{ "screen_name" : "VancouverAqua" }
{ "screen_name" : "LaurieLogan" }
{ "screen_name" : "CenturyPlazaVan" }
{ "screen_name" : "GlotmanSimpson" }
{ "screen_name" : "dhmakwana" }
{ "screen_name" : "carlashore" }
{ "screen_name" : "dereklacroix" }
{ "screen_name" : "5571" }
{ "screen_name" : "YeomanEddie" }
{ "screen_name" : "jptong" }
{ "screen_name" : "Moonflowere" }
{ "screen_name" : "PaullPeterson" }
{ "screen_name" : "sageaaron" }
{ "screen_name" : "604homesguy" }
{ "screen_name" : "thenetworkhub" }
{ "screen_name" : "rachelmarcuse" }
{ "screen_name" : "CyG_accounts" }
{ "screen_name" : "myredbike" }
{ "screen_name" : "ed_kwong" }
{ "screen_name" : "freedryk" }
{ "screen_name" : "zachrenwick" }
{ "screen_name" : "anatingor" }
{ "screen_name" : "barbfloden" }
{ "screen_name" : "gardencitycabs" }
{ "screen_name" : "Greg_Tri2Fight" }
{ "screen_name" : "fabulavancouver" }
{ "screen_name" : "VancouverSavvy" }
{ "screen_name" : "vinylcut" }
{ "screen_name" : "leahgregg" }
{ "screen_name" : "yoyomamadotca" }
{ "screen_name" : "bwabwa" }
{ "screen_name" : "reneestephen" }
{ "screen_name" : "justin_fung" }
{ "screen_name" : "MikuRestaurant" }
{ "screen_name" : "VancouverLocal" }
{ "screen_name" : "CBCVancouver" }
{ "screen_name" : "KevinJBowers" }
{ "screen_name" : "chelsetron" }
{ "screen_name" : "CiTRnews" }
{ "screen_name" : "hockey694" }
{ "screen_name" : "News1130radio" }
{ "screen_name" : "VogueTheatre" }
{ "screen_name" : "surreylibrary" }
{ "screen_name" : "TheatreUBC" }
{ "screen_name" : "VancouverCityTV" }
{ "screen_name" : "AprilPenney" }
{ "screen_name" : "VTOC" }
{ "screen_name" : "azeliamanners" }
{ "screen_name" : "jen_alderson" }
{ "screen_name" : "aerocar" }
{ "screen_name" : "aleidalee" }
{ "screen_name" : "kaequan" }
{ "screen_name" : "Helijet" }
{ "screen_name" : "freetransit" }
{ "screen_name" : "NorthShoreEMO" }
{ "screen_name" : "pacmedia" }
{ "screen_name" : "CTV_JonWoodward" }
{ "screen_name" : "neilhuff" }
{ "screen_name" : "agentblair" }
{ "screen_name" : "Amuse_events" }
{ "screen_name" : "JennyLeeSilver" }
{ "screen_name" : "notfauna" }
{ "screen_name" : "MrMortgages" }
{ "screen_name" : "brentgranby" }
{ "screen_name" : "tourism2010jobs" }
{ "screen_name" : "kpwerker" }
{ "screen_name" : "wowgals" }
{ "screen_name" : "Condoguys" }
{ "screen_name" : "wetcoast" }
{ "screen_name" : "MetroVancouver" }
{ "screen_name" : "emital" }
{ "screen_name" : "andreareimer" }
{ "screen_name" : "LDABC" }
{ "screen_name" : "taylorloren" }
{ "screen_name" : "MikeSoron" }
{ "screen_name" : "denise_luong" }
{ "screen_name" : "PaulLeBlanc" }
{ "screen_name" : "downtownvan" }
{ "screen_name" : "jamesglave" }
{ "screen_name" : "yewchi" }
{ "screen_name" : "heyrickie" }
{ "screen_name" : "CRNEprep" }
{ "screen_name" : "kristifuoco" }
{ "screen_name" : "victorngo" }
{ "screen_name" : "enniscath" }
{ "screen_name" : "2010Streetcar" }
{ "screen_name" : "BrightNightsVan" }
{ "screen_name" : "Burns_Bog" }
{ "screen_name" : "kaldinger" }
{ "screen_name" : "gvadirectory" }
{ "screen_name" : "alexwarrior" }
{ "screen_name" : "duckdeux" }
{ "screen_name" : "folkoasis" }
{ "screen_name" : "COPE378" }
{ "screen_name" : "MissKitty680" }
{ "screen_name" : "doteco" }
{ "screen_name" : "karljidder" }
{ "screen_name" : "BC_Rideshare" }
{ "screen_name" : "GainingGround10" }
{ "screen_name" : "amlalonde" }
{ "screen_name" : "Jason_Sew" }
{ "screen_name" : "ChoicesMarkets" }
{ "screen_name" : "LianeatWalker" }
{ "screen_name" : "EricoNascimento" }
{ "screen_name" : "counti8" }
{ "screen_name" : "CarpetCleanerBC" }
{ "screen_name" : "eekoCouriers" }
{ "screen_name" : "CityofVancouver" }
{ "screen_name" : "Clippernolan" }
{ "screen_name" : "STVNetwork" }
{ "screen_name" : "AckroydBP" }
{ "screen_name" : "twitcouver" }
{ "screen_name" : "Lady778" }
{ "screen_name" : "tothewestside" }
{ "screen_name" : "VanEconomic" }
